import PDFDocument from 'pdfkit';
import Asset from '../models/Asset.js';
import Rule from '../models/Rule.js';
import Contact from '../models/Contact.js';
import User from '../models/User.js';

const generateWillPDF = async (userId) => {
  const [user, assets, rules, contacts] = await Promise.all([
    User.findById(userId),
    Asset.find({ userId }),
    Rule.find({ userId }).populate('assetId', 'name platform type').populate('beneficiaryId', 'name email'),
    Contact.find({ userId })
  ]);

  const doc = new PDFDocument({ size: 'A4', margin: 60 });

  // Title
  doc.fontSize(28).font('Helvetica-Bold').text('DataWill', { align: 'center' });
  doc.fontSize(12).font('Helvetica').fillColor('#666').text('Digital Estate Summary', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(1);

  // Line
  doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor('#ddd').stroke();
  doc.moveDown(1);

  // Owner Info
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#0D1117').text('Account Holder');
  doc.moveDown(0.3);
  doc.fontSize(11).font('Helvetica').fillColor('#333');
  doc.text(`Name: ${user.name}`);
  doc.text(`Email: ${user.email}`);
  doc.text(`Account created: ${user.createdAt?.toLocaleDateString() || 'N/A'}`);
  doc.moveDown(1);

  // Assets
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#0D1117').text(`Digital Assets (${assets.length})`);
  doc.moveDown(0.3);
  if (assets.length === 0) {
    doc.fontSize(11).font('Helvetica').fillColor('#666').text('No assets registered.');
  } else {
    assets.forEach((a, i) => {
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#1A3A2A').text(`${i + 1}. ${a.name}`);
      doc.fontSize(10).font('Helvetica').fillColor('#666').text(`   Platform: ${a.platform || '—'} | Type: ${a.type} | Status: ${a.status}`);
    });
  }
  doc.moveDown(1);

  // Rules
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#0D1117').text(`Will Rules (${rules.length})`);
  doc.moveDown(0.3);
  if (rules.length === 0) {
    doc.fontSize(11).font('Helvetica').fillColor('#666').text('No rules defined.');
  } else {
    rules.forEach((r, i) => {
      const assetName = r.assetId?.name || 'Unknown';
      const beneficiary = r.beneficiaryId ? `→ ${r.beneficiaryId.name} (${r.beneficiaryId.email})` : '';
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#1A3A2A').text(`${i + 1}. ${assetName} — ${r.action.toUpperCase()}`);
      if (beneficiary) doc.fontSize(10).font('Helvetica').fillColor('#666').text(`   Beneficiary: ${beneficiary}`);
      if (r.description) doc.fontSize(10).font('Helvetica').fillColor('#666').text(`   Note: ${r.description}`);
    });
  }
  doc.moveDown(1);

  // Contacts
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#0D1117').text(`Trusted Contacts (${contacts.length})`);
  doc.moveDown(0.3);
  if (contacts.length === 0) {
    doc.fontSize(11).font('Helvetica').fillColor('#666').text('No contacts added.');
  } else {
    contacts.forEach((c, i) => {
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#1A3A2A').text(`${i + 1}. ${c.name}`);
      doc.fontSize(10).font('Helvetica').fillColor('#666').text(`   Email: ${c.email} | Role: ${c.role} | Relationship: ${c.relationship || '—'}`);
    });
  }
  doc.moveDown(2);

  // Footer
  doc.fontSize(9).font('Helvetica').fillColor('#999').text(
    'This document is a summary generated by DataWill. It does not constitute a legal will. Consult a legal professional for binding estate documents.',
    { align: 'center' }
  );

  doc.end();
  return doc;
};

export { generateWillPDF };
